services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.18.0
    container_name: filebeat
    user: root
    command:
      ["-e", "-c", "/usr/share/filebeat/filebeat.yml", "--strict.perms=false"]
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - /var/log/suricata/eve.json:/usr/share/filebeat/eve.json:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./wazuh.yml:/usr/share/filebeat/wazuh.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - soc-net
