include "application.secret.conf"

play.http.secret.key = "changeme-in-production"
play.http.context = "/"

search {
  uri = "http://elasticsearch:9200"
  index = "cortex"
}

auth {
  basic {
    realm = "Cortex"
    validator = "local"
  }
}

cortex {
  secret = "changeme-in-production"
}

storage {
  provider = "local"
  local.path = "/opt/cortex/data"
}
