input {
  file {
    id => "wazuh_alerts"
    path => "/var/ossec/logs/alerts/alerts.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
    mode => "tail"
    stat_interval => "1"
    ecs_compatibility => "disabled"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "wazuh-alerts-4.x-%{+YYYY.MM.dd}"
    user => "${ELASTICSEARCH_USERNAME}"
    password => "${ELASTIC_PASSWORD}"
    template => "/etc/logstash/templates/wazuh.json"
    template_name => "wazuh"
    template_overwrite => true
    ssl => false
  }
}
